
CREATE TABLE if not EXISTS BOOKS (
  ID            INT          NOT NULL  AUTO_INCREMENT PRIMARY KEY
  ,ISBN         VARCHAR(13)  NOT NULL  CONSTRAINT books_isbn_uc UNIQUE
  ,AUTHOR       VARCHAR(255) NOT NULL
  ,TITLE        VARCHAR(255) NOT NULL
  ,DESCRIPTION  VARCHAR(750) NOT NULL
  ,GENRE	      VARCHAR(255) NOT NULL
  ,PRICE        DOUBLE       NOT NULL
  ,PUBLISHER    VARCHAR(255)
  ,PUBLISHED_ON DATE
);